#!/usr/bin/env python3
"""Generate aes67_regs.h from a LiteX csr.csv.

The kernel module must never hard-code Wishbone addresses: they shift whenever
litex_soc/generate.py changes (e.g. enabling --ptp-in-software reorders CSRs).
This script turns the generated csr.csv into a C header of byte-address #defines
so the driver stays in lock-step with the gateware.

Usage:
    ./gen_regs.py litex_soc/build/aes67_bridge/csr.csv > aes67_regs.h
"""
import sys


def main():
    if len(sys.argv) != 2:
        sys.exit(f"usage: {sys.argv[0]} <csr.csv>")

    regs = []   # (NAME, addr)
    mems = []   # (NAME, addr)
    for line in open(sys.argv[1]):
        parts = [p.strip() for p in line.split(",")]
        if not parts or not parts[0]:
            continue
        kind = parts[0]
        if kind == "csr_register":
            regs.append((parts[1], int(parts[2], 0)))
        elif kind == "memory_region":
            mems.append((parts[1], int(parts[2], 0)))

    out = sys.stdout
    out.write("/* SPDX-License-Identifier: GPL-2.0 */\n")
    out.write("/* Auto-generated by gen_regs.py from csr.csv — DO NOT EDIT. */\n")
    out.write("#ifndef AES67_REGS_H\n#define AES67_REGS_H\n\n")

    out.write("/* CSR registers (byte addresses on the Wishbone bus). */\n")
    for name, addr in regs:
        out.write(f"#define AES67_REG_{name.upper():<40} 0x{addr:08x}u\n")

    out.write("\n/* Memory regions (byte base addresses). */\n")
    for name, addr in mems:
        out.write(f"#define AES67_MEM_{name.upper():<40} 0x{addr:08x}u\n")

    out.write("\n#endif /* AES67_REGS_H */\n")


if __name__ == "__main__":
    main()
