set_false_path -from [get_registers {*spictrl:\spigen:spictrl_inst|mac_address_o*}]
set_false_path -from [get_registers {*spictrl:\spigen:spictrl_inst|ip_address_o*}]
set_false_path -from [get_registers {*spictrl:\spigen:spictrl_inst|ptp_time_source_o*}]
set_false_path -from [get_registers {*spictrl:\spigen:spictrl_inst|ptp_log_sync_interval_o*}]
set_false_path -from [get_registers {*spictrl:\spigen:spictrl_inst|ptp_log_announce_interval_o*}]
set_false_path -from [get_registers {*spictrl:\spigen:spictrl_inst|ptp_priority_o*}]
set_false_path -from [get_registers {*spictrl:\spigen:spictrl_inst|ptp_clock_class_o*}]
set_false_path -from [get_registers {*spictrl:\spigen:spictrl_inst|ptp_clock_accuracy_o*}]