## SDC Constraints for AES67 FPGA
## Device: 10CL025YU256I7G (Cyclone 10 LP)
##
## Clock Structure:
##   c10_clk50m (50 MHz) -> PLL b2v_sysclocks -> sys_clk_125m (125 MHz)
##   c10_clk50m (50 MHz) -> PLL b2v_litex    -> litex_sys_clk (80 MHz)
##   enet_clk_125m (125 MHz) -> PLL b2v_rgmiiclks -> RGMII TX clocks
##   enet_rx_clk (125 MHz, 90° phase shifted by PHY)
##   gpio1 (24.576 MHz = 48kHz * 512 Audio MCLK)
##   Audio clocks generated by audioclock_generator (inst: b2v_audioclocks):
##     audio_mclk -> cnt(0) = clk_256fs (12.288 MHz, /2)
##     audio_mclk -> cnt(1) = clk_128fs ( 6.144 MHz, /4)
##     audio_mclk -> cnt(2) = clk_64fs  ( 3.072 MHz, /8)
##     audio_mclk -> cnt(8) = fs        (48 kHz,   /512)
##     audio_mclk (falling edge) -> bclk_f (12.288 MHz, registered on falling edge)

#**************************************************************
# Time Information
#**************************************************************

set_time_format -unit ns -decimal_places 3


#**************************************************************
# Create Clock
#**************************************************************

# Primary 50 MHz oscillator input to PLLs
create_clock -name {c10_clk50m} -period 20.000 -waveform { 0.000 10.000 } [get_ports {c10_clk50m}]

# Audio master clock from external PLL (48kHz * 512 = 24.576 MHz)
create_clock -name {audio_mclk} -period 40.690 -waveform { 0.000 20.345 } [get_ports {gpio1}]

# RGMII 125 MHz reference clock from PHY
create_clock -name {enet_clk_125m} -period 8.000 -waveform { 0.000 4.000 } [get_ports {enet_clk_125m}]


#**************************************************************
# Create Generated Clock
#**************************************************************

# PLL b2v_sysclocks output clk[0]: 125 MHz system clock (50 * 5 / 2)
create_generated_clock -name {sys_clk_125m} \
    -source [get_pins {b2v_sysclocks|altpll_component|auto_generated|pll1|inclk[0]}] \
    -duty_cycle 50.00 -multiply_by 5 -divide_by 2 \
    -master_clock {c10_clk50m} \
    [get_pins {b2v_sysclocks|altpll_component|auto_generated|pll1|clk[0]}]

# LiteX SoC PLL (b2v_litex) output: 80 MHz sys_clk (50 * 8 / 5)
create_generated_clock -name {litex_sys_clk} \
    -source [get_pins {b2v_litex|ALTPLL|auto_generated|pll1|inclk[0]}] \
    -multiply_by 8 -divide_by 5 \
    -master_clock {c10_clk50m} \
    [get_pins {b2v_litex|ALTPLL|auto_generated|pll1|clk[0]}]

# RGMII TX PLL (b2v_rgmiiclks) output clk[0]: 125 MHz TX internal clock
create_generated_clock -name {b2v_rgmiiclks|altpll_component|auto_generated|pll1|clk[0]} \
    -source [get_pins {b2v_rgmiiclks|altpll_component|auto_generated|pll1|inclk[0]}] \
    -duty_cycle 50.00 -multiply_by 1 -divide_by 1 \
    -master_clock {enet_clk_125m} \
    [get_pins {b2v_rgmiiclks|altpll_component|auto_generated|pll1|clk[0]}]

# RGMII TX PLL (b2v_rgmiiclks) output clk[1]: 125 MHz with 90° phase shift (for DDR TX timing)
create_generated_clock -name {b2v_rgmiiclks|altpll_component|auto_generated|pll1|clk[1]} \
    -source [get_pins {b2v_rgmiiclks|altpll_component|auto_generated|pll1|inclk[0]}] \
    -duty_cycle 50.00 -multiply_by 1 -divide_by 1 \
    -phase 90.0 \
    -master_clock {enet_clk_125m} \
    [get_pins {b2v_rgmiiclks|altpll_component|auto_generated|pll1|clk[1]}]

# Audio clocks from audioclock_generator (instance: b2v_audioclocks)
# All derived from the 9-bit free-running counter clocked by audio_mclk.
# Outputs are combinatorial from counter bits — Quartus models them as
# generated clocks on the Q output of the relevant counter register.

# cnt(0) -> clk_256fs / bclk_r : 12.288 MHz (audio_mclk / 2)
create_generated_clock -name {clk_256fs} \
    -source [get_ports {gpio1}] \
    -divide_by 2 \
    -master_clock {audio_mclk} \
    [get_registers {b2v_audioclocks|cnt[0]}]

# cnt(1) -> clk_128fs : 6.144 MHz (audio_mclk / 4)
create_generated_clock -name {clk_128fs} \
    -source [get_ports {gpio1}] \
    -divide_by 4 \
    -master_clock {audio_mclk} \
    [get_registers {b2v_audioclocks|cnt[1]}]

# cnt(2) -> clk_64fs : 3.072 MHz (audio_mclk / 8)
create_generated_clock -name {clk_64fs} \
    -source [get_ports {gpio1}] \
    -divide_by 8 \
    -master_clock {audio_mclk} \
    [get_registers {b2v_audioclocks|cnt[2]}]

# cnt(8) -> fs : 48 kHz (audio_mclk / 512)
create_generated_clock -name {fs} \
    -source [get_ports {gpio1}] \
    -divide_by 512 \
    -master_clock {audio_mclk} \
    [get_registers {b2v_audioclocks|cnt[8]}]

# bclk_f_r : 12.288 MHz, registered on falling edge of audio_mclk
# This register is clocked by the inverted mclk — declare as generated
# clock with invert so Quartus tracks timing correctly.
create_generated_clock -name {bclk_f} \
    -source [get_ports {gpio1}] \
    -divide_by 2 \
    -invert \
    -master_clock {audio_mclk} \
    [get_registers {b2v_audioclocks|bclk_f_r}]


#**************************************************************
# Set Clock Groups
#**************************************************************

# Clock domains:
# 1. System 125 MHz domain: c10_clk50m -> PLL b2v_sysclocks -> sys_clk_125m
# 2. LiteX SoC domain: c10_clk50m -> PLL b2v_litex -> litex_sys_clk (80 MHz)
# 3. Audio domain: audio_mclk and clocks from audioclock_generator (async external oscillator)
# 4. RGMII TX domain: enet_clk_125m -> PLL b2v_rgmiiclks -> TX clocks
# 5. RGMII RX domain: enet_rx_clk (from PHY, created in rgmii_io.sdc)
#
# Note: sys_clk_125m and litex_sys_clk share the same source (c10_clk50m)
# but have unrelated PLL outputs and no synchronous phase relationship,
# so they are treated as asynchronous.

set_clock_groups -asynchronous \
    -group [get_clocks {c10_clk50m sys_clk_125m}] \
    -group [get_clocks {litex_sys_clk}] \
    -group [get_clocks {audio_mclk clk_256fs clk_128fs clk_64fs fs bclk_f}] \
    -group [get_clocks {enet_clk_125m b2v_rgmiiclks|altpll_component|auto_generated|pll1|clk[0] b2v_rgmiiclks|altpll_component|auto_generated|pll1|clk[1]}]


#**************************************************************
# Set False Path
#**************************************************************

# --- MIIM Management Interface (slow async, ~2.5 MHz max) ---
set_false_path -from * -to [get_ports {enet_mdc}]
set_false_path -from * -to [get_ports {enet_mdio}]
set_false_path -from [get_ports {enet_mdio}] -to *
set_false_path -from * -to [get_ports {enet_resetn}]

# --- CDC synchronizers in PTP logic (inside ptp_module b2v_ptp) ---
set_false_path -from [get_registers {*b2v_ptp|b2v_pptx|tx_enable}] -to [get_registers {*b2v_ptp|b2v_controller|tx_en_i_meta}]
set_false_path -to [get_registers {*b2v_ptp|b2v_ptpparser|parse_ptp_packet_meta}]

# --- PTP is_leader/is_follower: litex_sys_clk -> sys_clk_125m ---
# Slow-changing configuration signals from LiteX SoC CSR to PTP modules
set_false_path -from [get_registers {*aes67_csr_ctrl_storage*}] -to [get_registers {*b2v_ptp|b2v_controller|*}]
set_false_path -from [get_registers {*aes67_csr_ctrl_storage*}] -to [get_registers {*b2v_ptp|b2v_ptpparser|*}]

# --- tx_router shadow register CDC (litex_sys_clk -> sys_clk_125m) ---
# Slow-changing config values updated only during stream setup
set_false_path -from [get_registers {*b2v_audiotx|b2v_tx_router|samples_per_packet_shadow[*][*]}] -to [get_registers {*b2v_audiotx|b2v_tx_router|samples_per_packet_sync[*][*]}]
set_false_path -from [get_registers {*b2v_audiotx|b2v_tx_router|threshold_shadow[*][*]}] -to [get_registers {*b2v_audiotx|b2v_tx_router|threshold_sync[*][*]}]

# --- tx_router tx_en CDC (tx_transmitter domain -> sys_clk) ---
set_false_path -to [get_registers {*b2v_audiotx|b2v_tx_router|tx_en_meta}]

# --- LiteX SoC reset signals - static during normal operation ---
set_false_path -from [get_registers {*aes67soc_reset_storage*}] -to *
set_false_path -from [get_registers {*aes67soc_reset_re*}] -to *

# --- LiteX SoC CSR registers crossing to FPGA logic domains ---
# All aes67_csr_* storage registers live in litex_sys_clk (80 MHz) and
# drive signals consumed in sys_clk_125m, enet_rx_clk, or audio_mclk domains.
# CDC is handled by 2-FF synchronizers in the FPGA logic.

# Control register (pll_ppb_start, ptp_is_leader, ptp_is_follower, eth_tx_request)
set_false_path -from [get_registers {*aes67_csr_ctrl_storage*}]

# Static configuration registers
set_false_path -from [get_registers {*aes67_csr_mac_addr*storage*}]
set_false_path -from [get_registers {*aes67_csr_ip_addr*storage*}]
set_false_path -from [get_registers {*aes67_csr_ptp_leader_id*storage*}]
set_false_path -from [get_registers {*aes67_csr_ptp_announce*storage*}]
set_false_path -from [get_registers {*aes67_csr_ptp_log*storage*}]
set_false_path -from [get_registers {*aes67_csr_ptp_time_source*storage*}]

# Stream config RAM write signals: litex_sys_clk -> FPGA logic
# These are directly driven from LiteX Wishbone bus outputs (no intermediate registers
# at the port boundary), so we match the SoC-internal source registers
set_false_path -from [get_registers {*stream_cfg*storage*}]

# --- Ethernet packet buffer CDC (mac_rx/mac_tx <-> litex_sys_clk) ---
# CDC handled by dual-port SRAM and synchronizers in LiteX EthPacketBuffer

# litex_eth_buffer_bridge (b2v_litex_eth): enet_rx_clk_125m -> litex_sys_clk
set_false_path -from [get_registers {*b2v_litex_eth|rx_overflow_reg*}]
set_false_path -from [get_registers {*b2v_litex_eth|rx_valid_reg*}]
set_false_path -from [get_registers {*b2v_litex_eth|buf_rx_len_o[*]}]

# LiteX SoC internal RX buffer CDC synchronizers
set_false_path -to [get_registers {*eth_buf_rx_valid_meta*}]
set_false_path -to [get_registers {*eth_buf_rx_len_latched*}]

# LiteX SoC TX buffer length and ack crossing litex_sys_clk -> mac_tx
set_false_path -from [get_registers {*eth_buf_tx_len*storage*}]
set_false_path -from [get_registers {*eth_buf_rx_ack*storage*}]

# --- I/O port false paths (directly driven by LiteX SoC, no FPGA-side timing) ---
# Serial UARTs
set_false_path -from * -to [get_ports {arduino_io2}]
set_false_path -from [get_ports {arduino_io1}] -to *
#set_false_path -from * -to [get_ports {gpio4}]
#set_false_path -from [get_ports {arduino_io3}] -to *

# I2C (directly connected to LiteX SoC, open-drain, slow)
set_false_path -from * -to [get_ports {gpio26 gpio27 gpio[26] gpio[27]}]
set_false_path -from [get_ports {gpio26 gpio27 gpio[26] gpio[27]}] -to *
set_false_path -from * -to [get_ports {gpio24 gpio23 gpio[24] gpio[23]}]
set_false_path -from [get_ports {gpio23 gpio24 gpio[24] gpio[23]}] -to *
# SPI (directly connected to LiteX SoC, max ~400 kHz for SD card init)
#set_false_path -from * -to [get_ports {gpio5 gpio6 gpio7}]
#set_false_path -from [get_ports {gpio8}] -to *

# HyperRAM (LiteX SDR PHY, 4:1 ratio, all logic in litex_sys_clk domain)
# Internal register-to-register timing is covered by litex_sys_clk (12.5ns).
# I/O paths need max_delay constraints to ensure registers are placed in/near
# I/O cells, preventing excessive routing delay that causes read data errors.
#
# Control signals (active before/after transfers, not timing-critical)
set_false_path -from * -to [get_ports {hbus_rstn hbus_cs2n}]
#
# Clock output: must have minimal and matched skew between P/N
set_max_delay -from [get_clocks {litex_sys_clk}] -to [get_ports {hbus_clk0_p}] 6.0
set_max_delay -from [get_clocks {litex_sys_clk}] -to [get_ports {hbus_clk0_n}] 6.0
#
# DQ output: data must be stable before HyperRAM samples on hbus_clk edge
set_max_delay -from [get_clocks {litex_sys_clk}] -to [get_ports {hbus_dq[*]}] 6.0
#
# DQ input: data from HyperRAM must meet setup to litex_sys_clk register
set_max_delay -from [get_ports {hbus_dq[*]}] -to [get_clocks {litex_sys_clk}] 6.0
#
# RWDS output: strobe/mask timing during writes
set_max_delay -from [get_clocks {litex_sys_clk}] -to [get_ports {hbus_rwds}] 6.0
#
# RWDS input: strobe edge detection must meet setup to litex_sys_clk
set_max_delay -from [get_ports {hbus_rwds}] -to [get_clocks {litex_sys_clk}] 6.0

# User LED
set_false_path -from * -to [get_ports {user_led[*]}]

# Reset input
set_false_path -from [get_ports {c10_resetn}] -to *


#**************************************************************
# Set Multicycle Path
#**************************************************************



#**************************************************************
# Set Maximum Delay
#**************************************************************



#**************************************************************
# Set Minimum Delay
#**************************************************************



#**************************************************************
# Set Input Transition
#**************************************************************

derive_pll_clocks
derive_clock_uncertainty

# --- LiteX SoC internal PLL (auto-derived by derive_pll_clocks) ---
# The PLL inside litex_soc (b2v_litex) generates the SoC's system clock from clk50.
# derive_pll_clocks creates this clock automatically, but it doesn't exist yet
# when the main set_clock_groups runs above. Declare it asynchronous to all
# other domains here, after derive_pll_clocks has created it.
set_clock_groups -asynchronous \
    -group [get_clocks {c10_clk50m sys_clk_125m}] \
    -group [get_clocks {b2v_litex|ALTPLL|auto_generated|pll1|clk[0]}] \
    -group [get_clocks {audio_mclk clk_256fs clk_128fs clk_64fs fs bclk_f}] \
    -group [get_clocks {enet_clk_125m b2v_rgmiiclks|altpll_component|auto_generated|pll1|clk[0] b2v_rgmiiclks|altpll_component|auto_generated|pll1|clk[1]}]


source ./rgmii_phy_if.sdc
source ./rgmii_io.sdc

# RGMII interface
constrain_rgmii_input_pins "enet" "enet_rx_clk" "enet_rx_dv enet_rx_d*"
constrain_rgmii_output_pins "enet" "b2v_rgmiiclks|altpll_component|auto_generated|pll1|clk[0]" "enet_tx_clk" "enet_tx_en enet_tx_d*"
