#!/usr/bin/env python3
"""Extract the FPGA configuration data blob from a Quartus JTAG SVF.


This extracts that data as a raw binary blob in shift order. SVF (like JTAG)
shifts the least-significant bit of the value first, so the blob is the value's
little-endian byte representation: byte i, bit b holds the (8*i + b)-th bit to
shift. The firmware shifts it out byte by byte, LSB first, reproducing exactly
what the USB-Blaster does.
"""
import re
import sys


def main():
    if len(sys.argv) not in (3, 4):
        sys.exit("usage: svf_to_bin.py <input.svf> <output.bin> [usercode.h]")
    svf_path, out_path = sys.argv[1], sys.argv[2]

    with open(svf_path) as f:
        text = f.read()

    # The configuration data is the largest SDR-TDI payload in the file.
    best = None
    for m in re.finditer(r"SDR\s+(\d+)\s+TDI\s+\(([0-9A-Fa-f\s]+?)\)", text):
        nbits = int(m.group(1))
        if best is None or nbits > best[0]:
            best = (nbits, m.group(2))

    if best is None:
        sys.exit("svf_to_bin: no 'SDR <n> TDI (...)' statement in " + svf_path)

    nbits, hexdata = best
    if nbits % 8:
        sys.exit("svf_to_bin: SDR length %d bits is not a byte multiple" % nbits)

    value = int(re.sub(r"\s+", "", hexdata), 16)
    blob = value.to_bytes(nbits // 8, "little")  # bit 0 shifted first

    with open(out_path, "wb") as f:
        f.write(blob)

    # Emit the USERCODE (Quartus "Auto Usercode" = programming-file checksum,
    # noted as `!NOTE "USERCODE" "hhhhhhhh"`) so the firmware can read the
    # device's USERCODE register back after configuration and verify it. A
    # value of 0 means the SVF carried no USERCODE note (verification off).
    if len(sys.argv) == 4:
        m = re.search(r'NOTE\s+"USERCODE"\s+"([0-9A-Fa-f]+)"', text)
        usercode = int(m.group(1), 16) if m else 0
        with open(sys.argv[3], "w") as f:
            f.write("/* Generated by svf_to_bin.py — do not edit. */\n")
            f.write("#define FPGA_JTAG_USERCODE 0x%08Xu\n" % usercode)


if __name__ == "__main__":
    main()
