-- miirmii.vhd

-- Generated using ACDS version 25.1 1129

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity miirmii is
	port (
		ena_10      : in  std_logic                    := '0';             --                    MACSPEED.ena_10
		RefClk      : in  std_logic                    := '0';             --                  clock_sink.clk
		m_tx_en     : in  std_logic                    := '0';             --               mii_interface.mii_tx_en
		m_tx_d      : in  std_logic_vector(3 downto 0) := (others => '0'); --                            .mii_tx_d
		m_tx_err    : in  std_logic                    := '0';             --                            .mii_tx_err
		m_rx_en     : out std_logic;                                       --                            .mii_rx_dv
		m_rx_d      : out std_logic_vector(3 downto 0);                    --                            .mii_rx_d
		m_rx_err    : out std_logic;                                       --                            .mii_rx_err
		m_rx_crs    : out std_logic;                                       --                            .mii_crs
		m_rx_col    : out std_logic;                                       --                            .mii_col
		rx_clk      : out std_logic;                                       -- pcs_mac_rx_clock_connection.clk
		tx_clk      : out std_logic;                                       -- pcs_mac_tx_clock_connection.clk
		Rstn        : in  std_logic                    := '0';             --                  reset_sink.reset_n
		rmii_crs_dv : in  std_logic                    := '0';             --              rmii_interface.crs
		rmii_rx_d   : in  std_logic_vector(1 downto 0) := (others => '0'); --                            .rxdata
		rmii_rx_err : in  std_logic                    := '0';             --                            .rxerror
		rmii_tx_en  : out std_logic;                                       --                            .txenable
		rmii_tx_d   : out std_logic_vector(1 downto 0)                     --                            .txdata
	);
end entity miirmii;

architecture rtl of miirmii is
	component intel_fpga_mii2rmii is
		generic (
			RX_FIXED_THROUGHPUT : boolean := false;
			MBPS                : boolean := true;
			MAC_SPEED           : boolean := true
		);
		port (
			RefClk      : in  std_logic                    := 'X';             -- clk
			Rstn        : in  std_logic                    := 'X';             -- reset_n
			m_tx_en     : in  std_logic                    := 'X';             -- mii_tx_en
			m_tx_d      : in  std_logic_vector(3 downto 0) := (others => 'X'); -- mii_tx_d
			m_tx_err    : in  std_logic                    := 'X';             -- mii_tx_err
			m_rx_en     : out std_logic;                                       -- mii_rx_dv
			m_rx_d      : out std_logic_vector(3 downto 0);                    -- mii_rx_d
			m_rx_err    : out std_logic;                                       -- mii_rx_err
			m_rx_crs    : out std_logic;                                       -- mii_crs
			m_rx_col    : out std_logic;                                       -- mii_col
			rmii_crs_dv : in  std_logic                    := 'X';             -- crs
			rmii_rx_d   : in  std_logic_vector(1 downto 0) := (others => 'X'); -- rxdata
			rmii_rx_err : in  std_logic                    := 'X';             -- rxerror
			rmii_tx_en  : out std_logic;                                       -- txenable
			rmii_tx_d   : out std_logic_vector(1 downto 0);                    -- txdata
			ena_10      : in  std_logic                    := 'X';             -- ena_10
			rx_clk      : out std_logic;                                       -- clk
			tx_clk      : out std_logic                                        -- clk
		);
	end component intel_fpga_mii2rmii;

begin

	fpga_mii2rmii_0 : component intel_fpga_mii2rmii
		generic map (
			RX_FIXED_THROUGHPUT => true,
			MBPS                => true,
			MAC_SPEED           => true
		)
		port map (
			RefClk      => RefClk,      --                  clock_sink.clk
			Rstn        => Rstn,        --                  reset_sink.reset_n
			m_tx_en     => m_tx_en,     --               mii_interface.mii_tx_en
			m_tx_d      => m_tx_d,      --                            .mii_tx_d
			m_tx_err    => m_tx_err,    --                            .mii_tx_err
			m_rx_en     => m_rx_en,     --                            .mii_rx_dv
			m_rx_d      => m_rx_d,      --                            .mii_rx_d
			m_rx_err    => m_rx_err,    --                            .mii_rx_err
			m_rx_crs    => m_rx_crs,    --                            .mii_crs
			m_rx_col    => m_rx_col,    --                            .mii_col
			rmii_crs_dv => rmii_crs_dv, --              rmii_interface.crs
			rmii_rx_d   => rmii_rx_d,   --                            .rxdata
			rmii_rx_err => rmii_rx_err, --                            .rxerror
			rmii_tx_en  => rmii_tx_en,  --                            .txenable
			rmii_tx_d   => rmii_tx_d,   --                            .txdata
			ena_10      => ena_10,      --                    MACSPEED.ena_10
			rx_clk      => rx_clk,      -- pcs_mac_rx_clock_connection.clk
			tx_clk      => tx_clk       -- pcs_mac_tx_clock_connection.clk
		);

end architecture rtl; -- of miirmii
