## SDC Constraints for AES67 FPGA
## Device: 10CL025YU256I7G (Cyclone 10 LP)
##
## Clock Structure:
##   c10_clk50m (50 MHz) -> PLL sysclocks_inst -> sys_clk_125m (125 MHz)
##   c10_clk50m (50 MHz) -> PLL litex_soc_inst -> litex_sys_clk (80 MHz)
##   enet_clk_125m (125 MHz) -> PLL rgmiiclks_inst -> RGMII TX clocks
##   enet_rx_clk (125 MHz, 90° phase shifted by PHY)
##   gpio1 (24.576 MHz = 48kHz * 512 Audio MCLK)
##   Audio clocks generated by audioclock_generator (inst: aes67_top_inst|audioclocks_inst):
##     audio_mclk -> cnt(0) = clk_256fs (12.288 MHz, /2)
##     audio_mclk -> cnt(1) = clk_128fs ( 6.144 MHz, /4)
##     audio_mclk -> cnt(2) = clk_64fs  ( 3.072 MHz, /8)
##     audio_mclk -> cnt(8) = fs        (48 kHz,   /512)
##     audio_mclk (falling edge) -> bclk_f (12.288 MHz, registered on falling edge)

#**************************************************************
# Time Information
#**************************************************************

set_time_format -unit ns -decimal_places 3


#**************************************************************
# Create Clock
#**************************************************************

# Primary 50 MHz oscillator input to PLLs
create_clock -name {c10_clk50m} -period 20.000 -waveform { 0.000 10.000 } [get_ports {c10_clk50m}]


# RGMII 125 MHz reference clock from PHY
create_clock -name {enet_clk_125m} -period 8.000 -waveform { 0.000 4.000 } [get_ports {enet_clk_125m}]


#**************************************************************
# Create Generated Clock
#**************************************************************

# PLL sysclocks_inst output clk[0]: 125 MHz system clock (50 * 5 / 2)
create_generated_clock -name {sys_clk_125m} \
    -source [get_pins {sysclocks_inst|altpll_component|auto_generated|pll1|inclk[0]}] \
    -duty_cycle 50.00 -multiply_by 5 -divide_by 2 \
    -master_clock {c10_clk50m} \
    [get_pins {sysclocks_inst|altpll_component|auto_generated|pll1|clk[0]}]

# LiteX SoC PLL (litex_soc_inst) output: 80 MHz sys_clk (50 * 8 / 5)
create_generated_clock -name {litex_sys_clk} \
    -source [get_pins {litex_soc_inst|ALTPLL|auto_generated|pll1|inclk[0]}] \
    -multiply_by 8 -divide_by 5 \
    -master_clock {c10_clk50m} \
    [get_pins {litex_soc_inst|ALTPLL|auto_generated|pll1|clk[0]}]

# RGMII TX PLL (rgmiiclks_inst) output clk[0]: 125 MHz TX internal clock
create_generated_clock -name {rgmii_rx_pll} \
    -source [get_pins {rgmiiclks_inst|altpll_component|auto_generated|pll1|inclk[0]}] \
    -duty_cycle 50.00 -multiply_by 1 -divide_by 1 \
    -master_clock {enet_clk_125m} \
    [get_pins {rgmiiclks_inst|altpll_component|auto_generated|pll1|clk[0]}]

# RGMII TX PLL (rgmiiclks_inst) output clk[1]: 125 MHz with 90° phase shift (for DDR TX timing)
create_generated_clock -name {rgmii_tx_pll} \
    -source [get_pins {rgmiiclks_inst|altpll_component|auto_generated|pll1|inclk[0]}] \
    -duty_cycle 50.00 -multiply_by 1 -divide_by 1 \
    -phase 90.0 \
    -master_clock {enet_clk_125m} \
    [get_pins {rgmiiclks_inst|altpll_component|auto_generated|pll1|clk[1]}]




source ../../../sdc/audioclocks.sdc

#**************************************************************
# Set Clock Groups
#**************************************************************

# Clock domains:
# 1. System 125 MHz domain: c10_clk50m -> PLL sysclocks_inst -> sys_clk_125m
# 2. LiteX SoC domain: c10_clk50m -> PLL litex_soc_inst -> litex_sys_clk (80 MHz)
# 3. Audio domain: audio_mclk and clocks from audioclock_generator (async external oscillator)
# 4. RGMII TX domain: enet_clk_125m -> PLL rgmiiclks_inst -> TX clocks
# 5. RGMII RX domain: enet_rx_clk (from PHY, created in rgmii_io.sdc)
#
# Note: sys_clk_125m and litex_sys_clk share the same source (c10_clk50m)
# but have unrelated PLL outputs and no synchronous phase relationship,
# so they are treated as asynchronous.

set_clock_groups -asynchronous \
    -group [get_clocks {c10_clk50m sys_clk_125m}] \
    -group [get_clocks {litex_sys_clk}] \
    -group [get_clocks {audio_mclk clk_256fs clk_128fs clk_64fs fs bclk_f}] \
    -group [get_clocks {enet_clk_125m rgmii_rx_pll rgmiiclks_inst|altpll_component|auto_generated|pll1|clk[1] mac_tx_clock}] \
    -group [get_clocks {enet_rx_clk_125m}]


#**************************************************************
# Set False Path
#**************************************************************

# --- MIIM Management Interface (slow async, ~2.5 MHz max) ---
set_false_path -from * -to [get_ports {enet_mdc}]
set_false_path -from * -to [get_ports {enet_mdio}]
set_false_path -from [get_ports {enet_mdio}] -to *
set_false_path -from * -to [get_ports {enet_resetn}]


# User LED
set_false_path -from * -to [get_ports {user_led[*]}]

# Reset input
set_false_path -from [get_ports {c10_resetn}] -to *

# --- SPI config slave (arduino_io0..3, spigen variant of top_c10) ---
# SPI_SLAVE inside spictrl samples SCK/CS/MOSI with 2-FF synchronizers in the
# sys_clk_125m domain, so these are proper async inputs. MISO is launched
# from sys_clk_125m and read by the external master on its own SCK, also
# async with respect to the FPGA timing analyzer.
set_false_path -from [get_ports {arduino_io0}] -to *
set_false_path -from [get_ports {arduino_io1}] -to *
set_false_path -from [get_ports {arduino_io2}] -to *
set_false_path -from * -to [get_ports {arduino_io3}]


source ../../../sdc/hyperram.sdc
source ../../../sdc/ptp.sdc
source ../../../sdc/litex_csr.sdc
source ../../../sdc/spictrl.sdc
#**************************************************************
# Set Multicycle Path
#**************************************************************




#**************************************************************
# Set Maximum Delay
#**************************************************************



#**************************************************************
# Set Minimum Delay
#**************************************************************



#**************************************************************
# Set Input Transition
#**************************************************************

derive_pll_clocks
derive_clock_uncertainty

source ../../../sdc/rgmii_phy_if.sdc
source ../../../sdc/rgmii_io.sdc

# RGMII interface — these procs create enet_rx_clk_125m and enet_tx_clk_125m
constrain_rgmii_input_pins "enet" "enet_rx_clk" "enet_rx_dv enet_rx_d*"
constrain_rgmii_output_pins "enet" "rgmii_tx_pll" "enet_tx_clk" "enet_tx_en enet_tx_d*"

# Final clock group declaration — after derive_pll_clocks and rgmii_io.sdc procs,
# so all clocks now exist. litex_sys_clk is the manually-defined name for the
# LiteX SoC PLL output (derive_pll_clocks skips it because it already exists).
set_clock_groups -asynchronous \
    -group [get_clocks {c10_clk50m sys_clk_125m}] \
    -group [get_clocks {litex_sys_clk}] \
    -group [get_clocks {audio_mclk clk_256fs clk_128fs clk_64fs fs bclk_f}] \
    -group [get_clocks {enet_clk_125m rgmii_tx_pll mac_tx_clock}] \
    -group [get_clocks {enet_rx_clk_125m rgmii_rx_pll}]
