// Copyright (C) 2025  Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Altera and sold by Altera or its authorized distributors.  Please
// refer to the Altera Software License Subscription Agreements 
// on the Quartus Prime software download page.


// Generated by Quartus Prime Version 25.1 (Build Build 1129 10/21/2025)
// Created on Sat Apr 11 17:39:05 2026

rmii_phy_if rmii_phy_if_inst
(
	.rstn_async(rstn_async_sig) ,	// input  rstn_async_sig
	.mode_speed(mode_speed_sig) ,	// input  mode_speed_sig
	.mac_mii_crs(mac_mii_crs_sig) ,	// output  mac_mii_crs_sig
	.mac_mii_rxrst(mac_mii_rxrst_sig) ,	// output  mac_mii_rxrst_sig
	.mac_mii_rxc(mac_mii_rxc_sig) ,	// output  mac_mii_rxc_sig
	.mac_mii_rxdv(mac_mii_rxdv_sig) ,	// output  mac_mii_rxdv_sig
	.mac_mii_rxer(mac_mii_rxer_sig) ,	// output  mac_mii_rxer_sig
	.mac_mii_rxd(mac_mii_rxd_sig) ,	// output [3:0] mac_mii_rxd_sig
	.mac_mii_txrst(mac_mii_txrst_sig) ,	// output  mac_mii_txrst_sig
	.mac_mii_txc(mac_mii_txc_sig) ,	// output  mac_mii_txc_sig
	.mac_mii_txen(mac_mii_txen_sig) ,	// input  mac_mii_txen_sig
	.mac_mii_txer(mac_mii_txer_sig) ,	// input  mac_mii_txer_sig
	.mac_mii_txd(mac_mii_txd_sig) ,	// input [3:0] mac_mii_txd_sig
	.phy_rmii_ref_clk(phy_rmii_ref_clk_sig) ,	// input  phy_rmii_ref_clk_sig
	.phy_rmii_crsdv(phy_rmii_crsdv_sig) ,	// input  phy_rmii_crsdv_sig
	.phy_rmii_rxer(phy_rmii_rxer_sig) ,	// input  phy_rmii_rxer_sig
	.phy_rmii_rxd(phy_rmii_rxd_sig) ,	// input [1:0] phy_rmii_rxd_sig
	.phy_rmii_txen(phy_rmii_txen_sig) ,	// output  phy_rmii_txen_sig
	.phy_rmii_txd(phy_rmii_txd_sig) 	// output [1:0] phy_rmii_txd_sig
);

