## SDC Constraints for AES67 FPGA — CYC1000 (RMII)
## Device: 10CL025YU256I7G (Cyclone 10 LP)
##
## Clock Structure:
##   c10_clk12m (12 MHz) -> PLL sysclocks_inst -> sys_clk_125m (125 MHz)
##   c10_clk12m (12 MHz) -> PLL litex_soc_inst -> litex_sys_clk
##   phy_rmii_ref_clk (50 MHz) -> rmii_phy_if_inst -> mac_mii_rxc (25 MHz, /2)
##   phy_rmii_ref_clk (50 MHz) -> rmii_phy_if_inst -> mac_mii_txc (25 MHz, /2)
##   gpio1 (24.576 MHz = 48kHz * 512 Audio MCLK)
##   Audio clocks generated by audioclock_generator (inst: aes67_top_inst|audioclocks_inst):
##     audio_mclk -> cnt(0) = clk_256fs (12.288 MHz, /2)
##     audio_mclk -> cnt(1) = clk_128fs ( 6.144 MHz, /4)
##     audio_mclk -> cnt(2) = clk_64fs  ( 3.072 MHz, /8)
##     audio_mclk -> cnt(8) = fs        (48 kHz,   /512)
##     audio_mclk (falling edge) -> bclk_f (12.288 MHz, registered on falling edge)

#**************************************************************
# Time Information
#**************************************************************

set_time_format -unit ns -decimal_places 3


#**************************************************************
# Create Clock
#**************************************************************

# Primary 12 MHz oscillator input to PLLs
create_clock -name {c10_clk12m} -period 83.333 -waveform { 0.000 41.665 } [get_ports {c10_clk12m}]

# RMII 50 MHz reference clock from PHY (external, asynchronous to c10_clk12m)
create_clock -name {phy_rmii_ref_clk} -period 20.000 -waveform { 0.000 10.000 } [get_ports {phy_rmii_ref_clk}]



#**************************************************************
# Create Generated Clock
#**************************************************************

# PLL sysclocks_inst output clk[0]: 125 MHz system clock (50 * 5 / 2)
create_generated_clock -name {sys_clk_125m} \
    -source [get_pins {*top_inst|\sysclkgen12:sysclks_altpll_12m_in_inst|altpll_component|auto_generated|pll1|inclk[0]}] \
    -duty_cycle 50.00 -multiply_by 125 -divide_by 12 \
    -master_clock {c10_clk12m} \
    [get_pins {*top_inst|\sysclkgen12:sysclks_altpll_12m_in_inst|altpll_component|auto_generated|pll1|clk[0]}]

# LiteX SoC PLL (litex_soc_inst) output: 50 MHz sys_clk (50 * 8 / 5)
create_generated_clock -name {litex_sys_clk} \
    -source [get_pins {*top_inst|\sysclkgen12:sysclks_altpll_12m_in_inst|altpll_component|auto_generated|pll1|inclk[0]}] \
    -multiply_by 25 -divide_by 4 \
    -master_clock {c10_clk12m} \
    [get_pins {top_inst|\sysclkgen12:sysclks_altpll_12m_in_inst|altpll_component|auto_generated|pll1|clk[1]}]

# RMII-to-MII generated clocks (50 MHz / 2 = 25 MHz register-divided clocks)
# mac_mii_rxc: MII RX clock used by MAC and aes67_top for receive path
create_generated_clock -name {mac_mii_rxc} \
    -source [get_ports {*phy_rmii_ref_clk*}] \
    -divide_by 2 \
    [get_registers {*mac_mii_rxc*}]

# mac_mii_txc: MII TX clock used by MAC and aes67_top for transmit path
create_generated_clock -name {mac_mii_txc} \
    -source [get_ports {*phy_rmii_ref_clk*}] \
    -divide_by 2 \
    [get_registers {*mac_mii_txc*}]


#source ../../../sdc/audioclocks.sdc

#**************************************************************
# Set Clock Groups
#**************************************************************

# Clock domains:
# 1. System 125 MHz domain: c10_clk12m -> PLL sysclocks_inst -> sys_clk_125m
# 2. LiteX SoC domain: c10_clk12m -> PLL litex_soc_inst -> litex_sys_clk
# 3. RMII/MII domain: phy_rmii_ref_clk (50 MHz) -> mac_mii_rxc, mac_mii_txc (25 MHz)
# 4. Audio domain: audio_mclk and clocks from audioclock_generator (async external oscillator)
#
# All four domains are asynchronous to each other.

set_clock_groups -asynchronous \
    -group [get_clocks {c10_clk12m sys_clk_125m}] \
    -group [get_clocks {litex_sys_clk}] \
    -group [get_clocks {phy_rmii_ref_clk mac_mii_rxc mac_mii_txc}] \
    -group [get_clocks {audio_mclk clk_256fs clk_128fs clk_64fs fs bclk_f}]


#**************************************************************
# Set False Path
#**************************************************************

# --- MIIM Management Interface (slow async, ~2.5 MHz max) ---
set_false_path -from * -to [get_ports {enet_mdc}]
set_false_path -from * -to [get_ports {enet_mdio}]
set_false_path -from [get_ports {enet_mdio}] -to *
set_false_path -from * -to [get_ports {enet_resetn}]

# --- CDC synchronizers in PTP logic (inside ptp_module ptp_inst) ---
set_false_path -from [get_registers {*ptp_inst|b2v_pptx|tx_enable}] -to [get_registers {*ptp_inst|b2v_controller|tx_en_i_meta}]
set_false_path -to [get_registers {*ptp_inst|b2v_ptpparser|parse_ptp_packet_meta}]

# --- PTP is_leader/is_follower: litex_sys_clk -> sys_clk_125m ---
# Slow-changing configuration signals from LiteX SoC CSR to PTP modules
set_false_path -from [get_registers {*aes67_csr_ctrl_storage*}] -to [get_registers {*ptp_inst|b2v_controller|*}]
set_false_path -from [get_registers {*aes67_csr_ctrl_storage*}] -to [get_registers {*ptp_inst|b2v_ptpparser|*}]

# --- tx_router shadow register CDC ---
# samples_per_packet_shadow and threshold_shadow no longer have separate _sync
# registers (CDC removed from tx_router). Shadow registers are written from
# config_wr_clk domain and read in sys_clk — covered by stream_cfg false_path below.

# --- tx_router tx_en CDC (tx_transmitter domain -> sys_clk) ---
set_false_path -to [get_registers {*audiotx_inst|b2v_tx_router|tx_en_meta}]

# --- LiteX SoC reset signals - static during normal operation ---
set_false_path -from [get_registers {*aes67soc_reset_storage*}] -to *
set_false_path -from [get_registers {*aes67soc_reset_re*}] -to *

# --- LiteX SoC CSR registers crossing to FPGA logic domains ---
# All aes67_csr_* storage registers live in litex_sys_clk (80 MHz) and
# drive signals consumed in sys_clk_125m, enet_rx_clk, or audio_mclk domains.
# CDC is handled by 2-FF synchronizers in the FPGA logic.

# Control register (pll_ppb_start, ptp_is_leader, ptp_is_follower, eth_tx_request)
set_false_path -from [get_registers {*aes67_csr_ctrl_storage*}]

# Static configuration registers
set_false_path -from [get_registers {*aes67_csr_mac_addr*storage*}]
set_false_path -from [get_registers {*aes67_csr_ip_addr*storage*}]
set_false_path -from [get_registers {*aes67_csr_ptp_leader_id*storage*}]
set_false_path -from [get_registers {*aes67_csr_ptp_announce*storage*}]
set_false_path -from [get_registers {*aes67_csr_ptp_log*storage*}]
set_false_path -from [get_registers {*aes67_csr_ptp_time_source*storage*}]

# Stream config RAM write signals: litex_sys_clk -> FPGA logic
# The StreamConfigRAM is a Wishbone slave (not a CSR), so its write signals are
# driven directly from the SoC bus. The tx_router config_wr_clk_i is litex_sys_clk
# and writes are slow (stream setup only). The shadow registers in tx_router are
# covered by the async clock group separation (litex_sys_clk vs sys_clk_125m).

# --- Ethernet packet buffer CDC (mac_rx/mac_tx <-> litex_sys_clk) ---
# CDC handled by dual-port SRAM and synchronizers in LiteX EthPacketBuffer

# litex_eth_buffer_bridge (litex_eth_inst): enet_rx_clk_125m -> litex_sys_clk
set_false_path -from [get_registers {*litex_eth_inst|rx_overflow_reg*}]
set_false_path -from [get_registers {*litex_eth_inst|rx_valid_reg*}]
set_false_path -from [get_registers {*litex_eth_inst|buf_rx_len_o[*]}]

# LiteX SoC internal RX buffer CDC synchronizers
set_false_path -to [get_registers {*eth_buf_rx_valid_meta*}]
set_false_path -to [get_registers {*eth_buf_rx_len_latched*}]

# LiteX SoC TX buffer length and ack crossing litex_sys_clk -> mac_tx
set_false_path -from [get_registers {*eth_buf_tx_len*storage*}]
set_false_path -from [get_registers {*eth_buf_rx_ack*storage*}]

# --- I/O port false paths (directly driven by LiteX SoC, no FPGA-side timing) ---
# Serial UARTs
set_false_path -from * -to [get_ports {arduino_io2}]
set_false_path -from [get_ports {arduino_io1}] -to *
#set_false_path -from * -to [get_ports {gpio4}]
#set_false_path -from [get_ports {arduino_io3}] -to *

# I2C (directly connected to LiteX SoC, open-drain, slow)
set_false_path -from * -to [get_ports {i2c0_scl i2c0_sda}]
set_false_path -from [get_ports {i2c0_scl i2c0_sda}] -to *
set_false_path -from * -to [get_ports {i2c1_scl i2c1_sda}]
set_false_path -from [get_ports {i2c1_scl i2c1_sda}] -to *

# User LED
set_false_path -from * -to [get_ports {user_led[*]}]

# Reset input
set_false_path -from [get_ports {c10_resetn}] -to *


#**************************************************************
# Set Multicycle Path
#**************************************************************



#**************************************************************
# Set Maximum Delay
#**************************************************************



#**************************************************************
# Set Minimum Delay
#**************************************************************



#**************************************************************
# Set Input Transition
#**************************************************************

derive_pll_clocks
derive_clock_uncertainty

# Final clock group declaration — after derive_pll_clocks, so all clocks exist.
# litex_sys_clk is the manually-defined name for the LiteX SoC PLL output
# (derive_pll_clocks skips it because it already exists).
set_clock_groups -asynchronous \
    -group [get_clocks {c10_clk12m sys_clk_125m}] \
    -group [get_clocks {litex_sys_clk}] \
    -group [get_clocks {phy_rmii_ref_clk mac_mii_rxc mac_mii_txc}] \
    -group [get_clocks {audio_mclk clk_256fs clk_128fs clk_64fs fs bclk_f}] \
