## SDC Constraints for AES67 FPGA — CYC1000 (RMII)
## Device: 10CL025YU256I7G (Cyclone 10 LP)
##
## Clock Structure:
##   c10_clk12m (12 MHz) -> PLL sysclocks_inst -> sys_clk_125m (125 MHz)
##   c10_clk12m (12 MHz) -> PLL litex_soc_inst -> litex_sys_clk
##   phy_rmii_ref_clk (50 MHz) -> rmii_phy_if_inst -> mac_mii_rxc (25 MHz, /2)
##   phy_rmii_ref_clk (50 MHz) -> rmii_phy_if_inst -> mac_mii_txc (25 MHz, /2)
##   gpio1 (24.576 MHz = 48kHz * 512 Audio MCLK)
##   Audio clocks generated by audioclock_generator (inst: aes67_top_inst|audioclocks_inst):
##     audio_mclk -> cnt(0) = clk_256fs (12.288 MHz, /2)
##     audio_mclk -> cnt(1) = clk_128fs ( 6.144 MHz, /4)
##     audio_mclk -> cnt(2) = clk_64fs  ( 3.072 MHz, /8)
##     audio_mclk -> cnt(8) = fs        (48 kHz,   /512)
##     audio_mclk (falling edge) -> bclk_f (12.288 MHz, registered on falling edge)

#**************************************************************
# Time Information
#**************************************************************

set_time_format -unit ns -decimal_places 3
## SDC Constraints for AES67 FPGA
## Device: 10CL025YU256I7G (Cyclone 10 LP)
##
## Clock structure (this build: soctype = "spi", USE_EXTERNAL_PLL = "false"):
##   clock_i (50 MHz)        -> sysclks_altpll_50m_in_inst -> 125 MHz sys clock
##                                                         -> 80 MHz mcu_clk
##   phy_rgmii_enet_clk_125m -> rgmiiclks_inst -> phy_rgmii_enet_tx_clk (0deg)
##                                             -> internal TX clock     (90deg)
##   phy_rgmii_enet_rx_clk   (125 MHz, 90deg shifted by PHY)
##   pll_512fs_i             -> audio_mclk    (only USE_EXTERNAL_PLL = "true")
##   wallclock NCO           -> nco_mclk      (only USE_EXTERNAL_PLL = "false")
##
## SDC ordering note:
##   PLL atom pins (altpll_component|auto_generated|pll1|*) only appear after
##   derive_pll_clocks runs. So this file is structured:
##     1. board-input clocks (real ports)
##     2. derive_pll_clocks   -> creates all PLL outputs under auto names
##     3. sub-SDCs (audioclocks/ptp/hyperram/...) -- now that all clocks exist
##     4. RGMII timing procs  -> create derived TX clocks
##     5. false paths and final clock groups (every clock now exists)

set_time_format -unit ns -decimal_places 3

#**************************************************************
# 1. Board-input clocks
#**************************************************************

create_clock -name {c10_clk12m} -period 83.333 -waveform { 0.000 41.665 } [get_ports {c10_clk12m}]

# RMII 50 MHz reference clock from PHY (external, asynchronous to c10_clk12m)
create_clock -name {phy_rmii_ref_clk} -period 20.000 -waveform { 0.000 10.000 } [get_ports {D8}]

#**************************************************************
# 2. Auto-derive every PLL-internal clock
#**************************************************************
# Generates clocks for sysclks_altpll_50m_in_inst (125 MHz, 80 MHz, ...) and
# rgmiiclks_inst (TX 0deg, TX 90deg) under their atom names, e.g.
#   top_inst|\sysclkgen50:sysclks_altpll_50m_in_inst|altpll_component|auto_generated|pll1|clk[0]
#   top_inst|\rgmiigen:rgmiiclks_inst|altpll_component|auto_generated|pll1|clk[0]

derive_pll_clocks
derive_clock_uncertainty

# Hierarchy paths to PLL outputs we reference below. Quartus encodes the
# generate-statement label as "\<label>:" in the netlist; the backslash is
# part of the identifier, not a Tcl escape, so it stays literal in {braces}.
# clk[0] = 125 MHz sys_clk (data plane), clk[1] = mcu_clk (LiteX/CPU, ~75 MHz).
# These are async to each other (CSR CDC handled in RTL); keep in separate groups.
# (Both were clk[1] before, which put the same clock in two groups and made
#  Quartus drop the whole set_clock_groups -> no async separation at all.)
set sys_pll_clk0      {soc_top_inst|wb_bridge_top_inst|sysclk_pll_gen_inst|\sysclkgen12:sysclks_altpll_12m_in_inst|altpll_component|auto_generated|pll1|clk[0]}
set sys_pll_clk1      {soc_top_inst|wb_bridge_top_inst|sysclk_pll_gen_inst|\sysclkgen12:sysclks_altpll_12m_in_inst|altpll_component|auto_generated|pll1|clk[1]}
set sys_pll_clk2      {soc_top_inst|wb_bridge_top_inst|sysclk_pll_gen_inst|\sysclkgen12:sysclks_altpll_12m_in_inst|altpll_component|auto_generated|pll1|clk[2]}

create_generated_clock -name {mac_mii_rxc} \
    -source [get_ports {*phy_rmii_ref_clk*}] \
    -divide_by 2 \
    [get_registers {*mac_mii_rxc*}]

# mac_mii_txc: MII TX clock used by MAC and aes67_top for transmit path
create_generated_clock -name {mac_mii_txc} \
    -source [get_ports {*phy_rmii_ref_clk*}] \
    -divide_by 2 \
    [get_registers {*mac_mii_txc*}]
#**************************************************************
# 3. Per-feature sub-SDCs (after derive_pll_clocks)
#**************************************************************

#source ../../../sdc/audioclocks.sdc

source ../../../sdc/ptp.sdc
source ../../../sdc/litex_csr.sdc
#source ../../../sdc/spictrl.sdc


#**************************************************************
# 5a. SPI slave (control interface from MCU)
#**************************************************************
# spictrl is a SPI slave clocked by spictrl_clk_i (driven by the external
# MCU). It is internally double-synchronised into sys_clk (see spi_slave.vhd
# CDC chain), so we declare spictrl_clk_i as its own async clock and treat
# all paths between it and sys_clk as false.
#
# Conservative SPI rate: 25 MHz max (40 ns period). Bump if the MCU drives
# faster — but the spi_slave does CDC, not source-synchronous capture, so
# the input-delay numbers are mostly informational.

create_clock -name {spictrl_clk} -period 40.000 [get_ports {spictrl_clk_i}]

set_input_delay  -clock {spictrl_clk} -max 5 [get_ports {spictrl_mosi_i spictrl_cs_n_i}]
set_input_delay  -clock {spictrl_clk} -min 0 [get_ports {spictrl_mosi_i spictrl_cs_n_i}]
set_output_delay -clock {spictrl_clk} -max 5 [get_ports {spictrl_miso_o}]
set_output_delay -clock {spictrl_clk} -min 0 [get_ports {spictrl_miso_o}]

# IRQ to MCU is a level/edge with no critical timing.
set_false_path -from * -to [get_ports {spictrl_irq_n_o}]

#**************************************************************
# 5b. Audio I/O — synchronous to the audio clock domain
#**************************************************************
# All audio I/O is external to the FPGA but stays inside one source-
# synchronous domain (the FPGA generates both the audio clocks and the
# data/lrclk). The downstream ADC/DAC sees the same clock edges; FPGA
# internal launch/capture timing is what matters and is already covered
# by the audio clock declarations in audioclocks.sdc. We mark the pins
# false_path here so unconstrained-port reports stop flagging them.
#
# pll_256fs_rising / pll_256fs_falling : ADC/DAC bit clocks
# pll_512fs_o                           : MCLK passthrough (port to port)
# lrclk_o / lrclk_tdm_o                 : frame syncs
# tdm8out_0_o / tdm8out_1_o             : serial audio out
# tdm8in_0_i  / tdm8in_1_i              : serial audio in

#set_false_path -from * -to [get_ports {pll_256fs_rising pll_256fs_falling pll_512fs_o lrclk_o lrclk_tdm_o tdm8out_0_o tdm8out_1_o}]
#set_false_path -from [get_ports {tdm8in_0_i tdm8in_1_i}] -to *

#**************************************************************
# 5c. False paths — slow / async pins
#**************************************************************

# MIIM Management Interface (slow async, ~2.5 MHz max)
set_false_path -from * -to [get_ports {D6}]
set_false_path -from * -to [get_ports {D7}]
set_false_path -from [get_ports {D7}] -to *

# PHY reset (async output)
set_false_path -from * -to [get_ports {phy_rgmii_enet_resetn}]

# User LED (async, visual only)
set_false_path -from * -to [get_ports {user_led[*]}]

# ADDA board reset: adda_nRST port is currently disabled in topevalkit.vhd;
# re-add "set_false_path -from * -to [get_ports {adda_nRST}]" when re-enabled.

# Async reset input
set_false_path -from [get_ports {c10_resetn}] -to *

#**************************************************************
# 6. Asynchronous clock groups — final
#**************************************************************
# Domains:
#   - sys clock: clock_i + 125 MHz PLL output
#   - audio: audio_mclk + nco_mclk + derived (audio_mclk vs nco_mclk handled
#            -exclusive inside audioclocks.sdc)
#   - RGMII TX: PHY-tx port + the rgmii TX PLL clk[0]
#   - RGMII RX: PHY rx clock + virtual rx clock + derived rx clock
#
# Reference PLL outputs by their atom paths (same set ... above) — this is
# the only name they are guaranteed to have post-derive_pll_clocks.

# RGMII TX/RX clock objects are named enet_tx_clk_125m / enet_rx_clk_125m
# (created on the PHY clock ports by constrain_rgmii_*); the port names
# phy_rgmii_enet_tx_clk / phy_rgmii_enet_rx_clk are NOT clock objects, so they
# must not appear here (they were silently dropped as "could not be matched").
set_clock_groups -asynchronous \
    -group [get_clocks [list c10_clk12m $sys_pll_clk0]] \
    -group [get_clocks [list phy_rmii_ref_clk]] \
	 -group [get_clocks [list $sys_pll_clk1 $sys_pll_clk2]] \
    -group [get_clocks {spictrl_clk}]



